name: Trigger rebuild of StratoWeave Guide

# When there are changes to files under docs/ on main branch,
# trigger the workflow to rebuild the StratoWeave Guide
on:
  push:
    branches:
      - main
    paths:
      - 'zensical.toml'
      - 'docs/**'

jobs:
  trigger_web_rebuild:
    runs-on: ubuntu-latest

    steps:
      - name: "Trigger build of stratoweave.guide"
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: stratoweave/stratoweave.guide
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: main.yml
          ref: main
